language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository 'deb http://download.opensuse.org/repositories/security:/Zorp/xUbuntu_12.04/ ./'
  - wget -qO - http://download.opensuse.org/repositories/security:/Zorp/xUbuntu_12.04/Release.key | sudo apt-key add -
  - sudo apt-get update -qq

before_script:
  - sudo apt-get install -qq devscripts equivs
  - sudo mk-build-deps -i

script:
  - ./autogen.sh
  - ./configure --prefix=$HOME
  - make clean
  - make
  - make check
  - sudo add-apt-repository 'deb http://download.opensuse.org/repositories/openSUSE:/Tools/xUbuntu_12.04/ /'
  - wget -qO - http://download.opensuse.org/repositories/openSUSE:Tools/xUbuntu_12.04/Release.key | sudo apt-key add -
  - sudo apt-get update -qq
  - echo -e "" | sudo apt-get install osc
  - dpkg-buildpackage -S || true
  - echo -e "[general]\napiurl = https://api.opensuse.org\n[https://api.opensuse.org]\nuser = pfeiffersz\npass = $OBS_PASSWORD\n" > ~/.oscrc
  - cat ~/.oscrc
  - osc co $OBS_PROJECT:$OBS_SUBPROJECT/$OBS_PACKAGE
  - rm -f $OBS_PROJECT:$OBS_SUBPROJECT/$OBS_PACKAGE/*
  - mv ../$OBS_PACKAGE*.tar.gz $OBS_PROJECT:$OBS_SUBPROJECT/$OBS_PACKAGE
  - mv ../$OBS_PACKAGE*.dsc $OBS_PROJECT:$OBS_SUBPROJECT/$OBS_PACKAGE
  - echo -e "addFilter(\".*\") \n" >rpm/$OBS_PACKAGE.rpmlintrc
  - mv rpm/$OBS_PACKAGE.* $OBS_PROJECT:$OBS_SUBPROJECT/$OBS_PACKAGE
  - cd $OBS_PROJECT:$OBS_SUBPROJECT/$OBS_PACKAGE
  - osc addremove
after_success:
  - osc commit -m "TRAVIS $TRAVIS_JOB_ID"

env:
  global:
    - secure: "lvVaWeVS34BGosuG4V9T4Yih1ASvzZbpZKkR5QxG5YlDJf5UL8fbdhWNgRnQt87BtCDiFVeU6kPSQi9b7DgNINO29J5k6C1HeBiFwkQtx44Kpmkv07P0jP70WVJMFye1ARuUyTpDKPx+dLoD6x08pzCz8+kEeEBeiwjU7WzGlOI="
    - OBS_PROJECT=security:Zorp
    - OBS_SUBPROJECT=6.0
    - OBS_PACKAGE=libzorpll
    - secure: "dDT9rtWPh8iYO56qWqatuKRE+gk3xEKKZa/sKSAbb/PyHSsJLkDp9vA4e0+JQNStC4YA+X0L6m4bpt275TKee1ucQg47to/monHmr3FG1LAx6zm8Gq7/4PlFnOo1oxfjFZEUnwF/WNZxjf6Y99n65onKl8fUGknGFnAKf0dYxWo="

addons:
  coverity_scan:
    project:
      name: "balabit/libzorpll"
      description: "Build submitted via Travis CI"
    notification_email: coroner@pfeifferszilard.hu
    build_command_prepend: "./configure; make clean"
    build_command:   "make -j4"
    branch_pattern: 6.0.0
